name: macro_kit
description: A development-time macro system for Dart that generates code instantly for fast iteration without build_runner.
version: 0.5.9
version_code: 35
repository: https://github.com/rebaz94/macro_kit
topics:
  - codegen
  - macro
  - builder
  - development
  - tooling

environment:
  sdk: ">=3.9.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  meta: ^1.16.0
  analyzer: ^8.4.0
  analyzer_plugin: ^0.13.10
  analysis_server_plugin: ^0.3.3
  source_helper: ^1.3.8
  watcher: ^1.2.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3
  http: ^1.6.0
  collection: ^1.19.1
  change_case: ^2.2.0
  path: ^1.9.1
  logging: ^1.3.0
  hashlib: ^2.3.0
  dart_style: ^3.1.3
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3

executables:
  macro: