name: macro_kit
description: A development-time macro system for Dart that generates code instantly for fast iteration without build_runner.
version: 0.6.4
version_code: 41
repository: https://github.com/rebaz94/macro_kit
topics:
  - codegen
  - macro
  - builder
  - development
  - tooling

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  meta: ^1.17.0
  analyzer: ^9.0.0
  analysis_server_plugin: ^0.3.4
  source_helper: ^1.3.9
  watcher: ^1.2.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3
  http: ^1.6.0
  collection: ^1.19.1
  change_case: ^2.2.0
  path: ^1.9.1
  logging: ^1.3.0
  hashlib: ^2.3.0
  dart_style: ^3.1.3
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3

executables:
  macro: