name: macro_analyzer_plugin

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  macro_kit: ^0.1.3
#  macro_kit:
#    path: /Volumes/Projects/Server/swiftybase/macro

dev_dependencies:
  lints: ^6.0.0
